# Databricks App Configuration for MCP Server
# Using uvicorn to run FastMCP's streamable-http ASGI app

command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

resources:
  http:
    - name: mcp-endpoint
      port: 8000
      public: true
